version: '3'

tasks:
  check-all:
    desc: 'task check-all'
    cmds:
      - rye run isort --check-only .
      - rye run black --check .
      - rye run flake8 .
  lint:
    desc: 'task lint -- path/to/file'
    cmds:
      - rye run flake8 {{.CLI_ARGS}}
  fmt:
    desc: 'task fmt -- path/to/file'
    cmds:
      - rye run isort {{.CLI_ARGS}}
      - rye run black {{.CLI_ARGS}}
