on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'

      # NOTE: On the CI, using rye is not necessary; pip is utilized due to its caching capability.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.lock -r requirements-dev.lock

      - name: Check all
        run: |
          flake8 .
          isort . --check-only
          black --check .
